interface=wlan2
driver=nl80211
ssid=MIWIFI_2G_j6pu
bssid=02:11:22:33:44:51
ignore_broadcast_ssid=0
channel=11
hw_mode=g
beacon_int=100
dtim_period=2
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=miwifi2026
macaddr_acl=0
country_code=ES
ieee80211d=1
