interface=wlan1
driver=nl80211
ssid=TP-Link_D1CA
bssid=44:45:41:55:54:49
ignore_broadcast_ssid=0
channel=1
hw_mode=g
beacon_int=100
dtim_period=2
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=tplink2026
macaddr_acl=0
country_code=ES
ieee80211d=1
