interface=wlan1
driver=nl80211
ssid=espectro-core
bssid=52:54:46:33:48:53
channel=11
hw_mode=g
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=espectro2026
macaddr_acl=0
country_code=ES
ieee80211d=1
