interface=wlan16
driver=nl80211
ssid=Orange-5G-4F2A
bssid=52:54:46:33:48:55
channel=1
hw_mode=g
beacon_int=100
dtim_period=2
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=iotfleet2026
macaddr_acl=0
country_code=ES
ieee80211d=1
